apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: quay.io/atwatanmalikm/nginx:1.22.0
          command:
          - sh
          - -c
          - sleep 1d
          ports:
            - containerPort: 80
